
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmsnukxykjvnowdnfbml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tc251a3h5a2p2bm93ZG5mYm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTY3NzgsImV4cCI6MjA2MTY3Mjc3OH0.k5iI72gdSZtKYxwqRE4WywIyb2-rdOxTfNAdAUWiCD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
